# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Michael Burge
author: Michael Burge
email: michaelburge@pobox.com
description: Articles on software development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.michaelburge.us" # the base hostname & protocol for your site, e.g. http://example.com
twitter_usernames:
  - TheMichaelBurge

# Build settings
markdown: kramdown
#theme: main
plugins:
  - jekyll-feed
  - jekyll-sitemap

gems:
  - jekyll-octicons

defaults:
  - scope:
      path: "assets/javascripts"
    values:
      javascript: true
  - scope:
      path: "_posts"
    values:
      bio: 'Michael Burge has years of experience developing complex software, including custom compilers, data stores for "big data", and improving website performance. Take advantage of his extensive knowledge and experience; <a href="mailto:michaelburge@pobox.com">Hire Michael</a> for your big project today.'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
